// <auto-generated />
using System;
using BahadirMakina.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BahadirMakina.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Depo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Depolar", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.DepoHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HedefDepoId")
                        .HasColumnType("int");

                    b.Property<int?>("IsAdimiId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("IsEmriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IstasyonId")
                        .HasColumnType("int");

                    b.Property<int?>("KaynakDepoId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HedefDepoId");

                    b.HasIndex("IsAdimiId");

                    b.HasIndex("IsEmriId");

                    b.HasIndex("IstasyonId");

                    b.HasIndex("KaynakDepoId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("DepoHareketleri", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Hurda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HurdaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsAdimiId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("IsEmriId")
                        .HasColumnType("int");

                    b.Property<int?>("KaliteKontrolId")
                        .HasColumnType("int");

                    b.Property<int?>("KaynakDepoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sebep")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("TahminiMaliyetKaybi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsAdimiId");

                    b.HasIndex("IsEmriId");

                    b.HasIndex("KaliteKontrolId");

                    b.HasIndex("KaynakDepoId");

                    b.HasIndex("UrunId");

                    b.ToTable("Hurdalar", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsAdimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("CiktiDepoId")
                        .HasColumnType("int");

                    b.Property<int?>("CiktiUrunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("GirdiDepoId")
                        .HasColumnType("int");

                    b.Property<int?>("GirdiUrunId")
                        .HasColumnType("int");

                    b.Property<decimal>("HedefMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("IsEmriId")
                        .HasColumnType("int");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("int");

                    b.Property<bool>("KaliteKontrolGerekli")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KaliteKontrolTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OncekiAdimId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int?>("SorumluKullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("TamamlananMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CiktiDepoId");

                    b.HasIndex("CiktiUrunId");

                    b.HasIndex("GirdiDepoId");

                    b.HasIndex("GirdiUrunId");

                    b.HasIndex("IsEmriId");

                    b.HasIndex("IstasyonId");

                    b.HasIndex("OncekiAdimId");

                    b.HasIndex("SorumluKullaniciId");

                    b.ToTable("IsAdimlari", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsAdimiBilesen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilesenUrunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsAdimiId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BilesenUrunId");

                    b.HasIndex("IsAdimiId", "BilesenUrunId")
                        .IsUnique();

                    b.ToTable("IsAdimiBilesenleri", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsAdimiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EskiDurum")
                        .HasColumnType("int");

                    b.Property<int>("IsAdimiId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YeniDurum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsAdimiId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("IsAdimiLoglari", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsEmri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<decimal>("HedefMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HurdaMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsEmriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("TamamlananMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsEmriNo")
                        .IsUnique();

                    b.HasIndex("OlusturanKullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("IsEmirleri", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Istasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AktifIsAdimiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AktifIsAdimiId");

                    b.HasIndex("DepoId");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Istasyonlar", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.KaliteKontrol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<int>("IsAdimiId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KontrolEdenKullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("KontrolEdilenMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("KontrolTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("OnaylananMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RedMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RedSebebi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sonuc")
                        .HasColumnType("int");

                    b.Property<bool>("TekrarIslemBaslatildi")
                        .HasColumnType("bit");

                    b.Property<int>("TekrarIslenecekMiktar")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("IsAdimiId");

                    b.HasIndex("KontrolEdenKullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("KaliteKontroller", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Stok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("IsAdimiId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("IsEmriId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsAdimiId");

                    b.HasIndex("IsEmriId");

                    b.HasIndex("UrunId");

                    b.HasIndex("DepoId", "UrunId");

                    b.ToTable("Stoklar", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MinimumStok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Urunler", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.UrunAgaciAdim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiktiUrunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HedefDepoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("IstasyonTipi")
                        .HasColumnType("int");

                    b.Property<bool>("KaliteKontrolGerekli")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CiktiUrunId");

                    b.HasIndex("HedefDepoId");

                    b.HasIndex("UrunId", "Sira")
                        .IsUnique();

                    b.ToTable("UrunAgaciAdimlari", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.UrunAgaciGerekliBilesen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilesenUrunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BilesenUrunId");

                    b.HasIndex("UrunId", "BilesenUrunId")
                        .IsUnique();

                    b.ToTable("UrunAgaciGerekliBilesenler", (string)null);
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.DepoHareket", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "HedefDepo")
                        .WithMany()
                        .HasForeignKey("HedefDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "IsAdimi")
                        .WithMany("DepoHareketleri")
                        .HasForeignKey("IsAdimiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.IsEmri", "IsEmri")
                        .WithMany("DepoHareketleri")
                        .HasForeignKey("IsEmriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Istasyon", "Istasyon")
                        .WithMany()
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "KaynakDepo")
                        .WithMany("DepoHareketleri")
                        .HasForeignKey("KaynakDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("DepoHareketleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HedefDepo");

                    b.Navigation("IsAdimi");

                    b.Navigation("IsEmri");

                    b.Navigation("Istasyon");

                    b.Navigation("KaynakDepo");

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Hurda", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "IsAdimi")
                        .WithMany()
                        .HasForeignKey("IsAdimiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.IsEmri", "IsEmri")
                        .WithMany()
                        .HasForeignKey("IsEmriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.KaliteKontrol", "KaliteKontrol")
                        .WithMany()
                        .HasForeignKey("KaliteKontrolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "KaynakDepo")
                        .WithMany()
                        .HasForeignKey("KaynakDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IsAdimi");

                    b.Navigation("IsEmri");

                    b.Navigation("KaliteKontrol");

                    b.Navigation("KaynakDepo");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsAdimi", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "CiktiDepo")
                        .WithMany()
                        .HasForeignKey("CiktiDepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "CiktiUrun")
                        .WithMany()
                        .HasForeignKey("CiktiUrunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "GirdiDepo")
                        .WithMany()
                        .HasForeignKey("GirdiDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "GirdiUrun")
                        .WithMany()
                        .HasForeignKey("GirdiUrunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.IsEmri", "IsEmri")
                        .WithMany("IsAdimlari")
                        .HasForeignKey("IsEmriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Istasyon", "Istasyon")
                        .WithMany("IsAdimlari")
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "OncekiAdim")
                        .WithMany("SonrakiAdimlar")
                        .HasForeignKey("OncekiAdimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Kullanici", "SorumluKullanici")
                        .WithMany()
                        .HasForeignKey("SorumluKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CiktiDepo");

                    b.Navigation("CiktiUrun");

                    b.Navigation("GirdiDepo");

                    b.Navigation("GirdiUrun");

                    b.Navigation("IsEmri");

                    b.Navigation("Istasyon");

                    b.Navigation("OncekiAdim");

                    b.Navigation("SorumluKullanici");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsAdimiBilesen", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("BilesenUrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "IsAdimi")
                        .WithMany("GerekliBilesenler")
                        .HasForeignKey("IsAdimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsAdimi");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsAdimiLog", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "IsAdimi")
                        .WithMany("Loglar")
                        .HasForeignKey("IsAdimiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("IsAdimiLogs")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IsAdimi");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsEmri", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Istasyon", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "AktifIsAdimi")
                        .WithMany()
                        .HasForeignKey("AktifIsAdimiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AktifIsAdimi");

                    b.Navigation("Depo");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.KaliteKontrol", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "IsAdimi")
                        .WithMany("KaliteKontroller")
                        .HasForeignKey("IsAdimiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Kullanici", "KontrolEdenKullanici")
                        .WithMany("KaliteKontroller")
                        .HasForeignKey("KontrolEdenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("IsAdimi");

                    b.Navigation("KontrolEdenKullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Stok", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "Depo")
                        .WithMany("Stoklar")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.IsAdimi", "IsAdimi")
                        .WithMany()
                        .HasForeignKey("IsAdimiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.IsEmri", "IsEmri")
                        .WithMany()
                        .HasForeignKey("IsEmriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany("Stoklar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("IsAdimi");

                    b.Navigation("IsEmri");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.UrunAgaciAdim", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "CiktiUrun")
                        .WithMany()
                        .HasForeignKey("CiktiUrunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BahadirMakina.Domain.Entities.Depo", "HedefDepo")
                        .WithMany()
                        .HasForeignKey("HedefDepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany("UrunAgaciAdimlari")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CiktiUrun");

                    b.Navigation("HedefDepo");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.UrunAgaciGerekliBilesen", b =>
                {
                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "BilesenUrun")
                        .WithMany("BilesenOlduguUrunler")
                        .HasForeignKey("BilesenUrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BahadirMakina.Domain.Entities.Urun", "Urun")
                        .WithMany("GerekliOlduguUrunler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BilesenUrun");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Depo", b =>
                {
                    b.Navigation("DepoHareketleri");

                    b.Navigation("Stoklar");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsAdimi", b =>
                {
                    b.Navigation("DepoHareketleri");

                    b.Navigation("GerekliBilesenler");

                    b.Navigation("KaliteKontroller");

                    b.Navigation("Loglar");

                    b.Navigation("SonrakiAdimlar");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.IsEmri", b =>
                {
                    b.Navigation("DepoHareketleri");

                    b.Navigation("IsAdimlari");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Istasyon", b =>
                {
                    b.Navigation("IsAdimlari");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("DepoHareketleri");

                    b.Navigation("IsAdimiLogs");

                    b.Navigation("KaliteKontroller");
                });

            modelBuilder.Entity("BahadirMakina.Domain.Entities.Urun", b =>
                {
                    b.Navigation("BilesenOlduguUrunler");

                    b.Navigation("GerekliOlduguUrunler");

                    b.Navigation("Stoklar");

                    b.Navigation("UrunAgaciAdimlari");
                });
#pragma warning restore 612, 618
        }
    }
}
